### ISSUE TITLE
An exception is thrown when try to add new record

### ISSUE THREAD

**Issue by blackWins** [EasyAbp/Abp.Trees#12]
**Package version:**
Abp 7.3.0
EasyAbp.Abp.Trees 2.11.0

**Reproduce：**

first i create a record
```
CreateUpdateAddressBookDto: { displayName:"root1", parentId:null}

// return retult
{
  "displayName": "root1",
  "code": "00001",
  "level": 1,
  "parentId": null,
...
  "id": "e3ba59a4-ddb4-98e4-20b3-3a0c791aba8a"
}

// then add new one

CreateUpdateAddressBookDto: { displayName:"root1-1", parentId:"e3ba59a4-ddb4-98e4-20b3-3a0c791aba8a"}
```

An exception is thrown
```
2023-07-18 10:39:26.323 +08:00 [ERR] A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.DisplayName.
System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.Children.Parent.DisplayName.
   at System.Text.Json.ThrowHelper.ThrowJsonException_SerializerCycleDetected(Int32 maxDepth)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Volo.Abp.AspNetCore.Auditing.AbpAuditingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Uow.AbpUnitOfWorkMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Volo.Abp.AspNetCore.ExceptionHandling.AbpExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
2023-07-18 10:39:26.327 +08:00 [INF] Request finished HTTP/2 POST https://localhost:44397/api/app/address-book application/json 89 - 500 - application/json 765.0414ms
```
```
[Serializable]
public class CreateUpdateAddressBookDto
{
    public string DisplayName { get; set; }
    public Guid? ParentId { get; set; }
}

public class AddressBookAppService : CrudAppService<AddressBook, AddressBookDto, Guid, PagedAndSortedResultRequestDto, CreateUpdateAddressBookDto, CreateUpdateAddressBookDto>, IAddressBookAppService
{
    private readonly IAddressBookRepository _repository;

    public AddressBookAppService(IAddressBookRepository repository) : base(repository)
    {
        _repository = repository;
    }

}

public interface IAddressBookRepository : ITreeRepository<AddressBook>
{
}

public class AddressBookRepository : EfCoreTreeRepository<LianfkDbContext, AddressBook>, IAddressBookRepository
{
    public AddressBookRepository(IDbContextProvider<LianfkDbContext> dbContextProvider) : base(dbContextProvider)
    {
    }
}
```

**Comment by usoftadmin** [comment]
@blackWins Brother, I also encountered the same problem, how did you solve it?

**Comment by blackWins** [comment]
> @blackWins Brother, I also encountered the same problem, how did you solve it?
@usoftadmin 

1.Check the module `DependsOn(typeof(AbpTreesXxxModule))`  dependencies are config

`XxxEntityFrameworkCoreModule`, `XxxDomainSharedModule`, `XxxDomainModule`

2.Check `IYourRepository : ITreeRepository<YourEntity>`

3.Be sure `YourEntity:XxxEntity<Guid>,ITree<YourEntity>`

4.Be sure `XxxEntityFrameworkCoreModule` has config  `options.AddDefaultTreeRepositories();`

**Comment by usoftadmin** [comment]
I found the solution last year, the problem was due to a circular reference in EF navigation properties. At that time, the method I used was to specify the Json serialization configuration as ReferenceLoopHandling.Ignore
```
context.Services.AddControllers()
.AddNewtonsoftJson(
          options => {
              options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
          });
```
But this method doesn't work this year when using the net8 new framework, so I specified JsonIgnore to ignore referenced objects on the entity:
```
        [JsonIgnore]
        public virtual Geography? Parent { get; set; }
        [JsonIgnore]
        public virtual ICollection<Geography>? Children { get; set; }
```
**Attention:** To cite using System.Text.Json.Serialization; Instead of"NewtonsoftJson" Why, I don't know either.
